(require 'user-init-default)
(require 'user-init-packages)
(require 'user-init-clojure-mode)
(require 'user-init-cider)
(require 'user-init-magit)
(require 'user-init-paredit)
(require 'user-init-company)
(require 'user-init-themes)
(require 'user-init-helm)
(require 'user-init-helm-ag)
(require 'user-init-projectile)
(require 'user-init-helm-projectile)
(require 'user-init-rainbow-delimiters)
(require 'user-init-writeroom-mode)
;; (require 'user-init-flycheck-joker)

(provide 'user-init)
